### PR TITLE
Fixes some issues with the module

### PR DESCRIPTION
**Pull request by mattecapu**
Specifically
- Transpiling before publishing to remove this burden from the final user
- Broken import
- Updated dependencies
- Corrected a couple of typos

### CODE REVIEW

**Comment by DanielHuisman** [comment]
Thanks for reporting the broken import and outdated dependencies, I will fix those.
I will add transpiling as well, but I don't completely like your implementation.
Especially the test scripts are strange, so I will probably configure these scripts myself.

**Comment by mattecapu** [comment]
I fixed some typos also.
I moved react/react-dom to peerDependencies to have cleaner stack traces, less deep nesting in node_modules, and the same React version powering all the application.

**Comment by mattecapu** [comment]
What's the matter with transpiling?

**Comment by DanielHuisman** [comment]
Just a few minor things:
- I'd like to transpile to a `lib` directory instead of compressing everything to `index.js`
- I'm pretty sure you don't need to include `babel-register` after transpiling
- The test scripts should be unit tests and/or linters, not installing the module in a parent directory and requiring it (so it would proabably be better if you remove them from this PR)
- I haven't used `npm version` before, so I need to look into how it works, but that's just a personal issue

**Comment by DanielHuisman** [comment]
This project is no longer maintained, closing all issues/PRs.

**Pull request closed without merging**
